---
# - name: Removing 22 as listening port
#   lineinfile:
#     path: /etc/ssh/sshd_config
#     regexp: '^Port 22'
#     line: '#Port 22'
#     backup: yes
#   register: sshdport22
#

- name: Configuring sshd 
  tags: server,sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^{{item}}$'
    line: '{{item}}'
    backup: yes
  loop:
    - 'Port 443'
    - 'Port 20022'
    - 'PermitRootLogin {{ROOTLOGIN}}'
    - 'AllowGroups sshgroup root'
    - 'ClientAliveInterval 120'
    - 'ClientAliveCountMax 720'
    - 'MaxSessions 1000'
    - 'X11Forwarding yes'
    - 'MaxStartups 500'
    - 'GatewayPorts yes'
  register: sshd

- name: Configuring sshd for virtualbox clonezilla imaging server connection
  tags: server,sshd
  blockinfile:
    path: /etc/ssh/sshd_config
    backup: yes
    validate: /usr/sbin/sshd -T -f %s
    marker: "# {mark} ANSIBLE MANAGED BLOCK: imaging virtual clonezilla server"
    block: |
      Match Address 192.168.10.53
          PermitRootLogin yes
          PasswordAuthentication yes
  register: sshd_virtualserver
  
- name: Restart ssh service in case any config was done
  tags: server,sshd
  command:
    cmd: /etc/rc.d/rc.sshd restart
  when:
    sshd.changed == True or sshd_virtualserver.changed
  register: sshdrestart
  failed_when: "sshdrestart.rc not in [0, 255]"
