---
- name: Check if monit is installed
  tags: monit, common
  stat:
    path: /usr/bin/monit
  register: monit
  failed_when: not monit.stat.exists

# Commented out since installation is better done under the packages script
# - name: Installing monit if not installed
#   shell:
#     cmd: source /root/.bashrc; sbopkg -B -k -i monit
#   when:
#     monit.stat.exists == False
#   notify: Restart monit

- name: Adding option to read files in monit.d
  tags: monit, common
  lineinfile:
    path: /etc/monitrc
    regexp: '^{{item}}'
    line: '{{item}}/*'
  loop:
    - 'include /etc/monit.d'
  notify: Restart monit

- name: Make sure monitrc exists and has right permissions
  tags: monit, common
  file:
    path: /etc/monitrc
    mode: 0600

- name: Make sure /etc/monit.d exists
  tags: monit, common
  file:
    path: /etc/monit.d
    state: directory

- name: Copying auxiliary restart script
  tags: monit, common
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
    mode: 0755
  loop:
    - usr/local/bin/monit_restart.sh
  
- name: Adding monit to inittab to make it run always
  tags: monit, common
  lineinfile:
    path: /etc/inittab
    search_string: '{{item}}'
    line: '{{item}}'
  loop:
    - 'mo:2345:respawn:/usr/bin/monit -Ic /etc/monitrc'
  notify: Restart monit
  
- name: Copy config files
  tags: monit, common
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
    follow: yes
  loop:
    - etc/monit.d/common-monitrc
    - etc/monit.d/HPC-monitrc
  notify: Restart monit

- name: Activate monit service
  tags: monit, common
  file:
    path: /etc/rc.d/rc.monit
    mode: +x
  notify: Restart monit
