---
- name: Check if monit is installed
  tags: server,client,monit, common
  ansible.builtin.stat:
    path: /usr/bin/monit
  register: monit_stat
  #failed_when: not monit.stat.exists

- name: Status of monit installation
  tags: server,client,monit, common
  ansible.builtin.debug:
    msg: "Monit installed: {{ monit_stat }}"
  #when: monit_stat.stat.exists == false


# Commented out since installation is better done under the packages script
- name: Installing monit if not installed
  tags: server,client,monit, common
  shell:
    cmd: source /root/.bashrc; sbopkg -B -k -i monit
  when:
    monit_stat.stat.exists == false
  notify: Restart monit

- name: Adding option to read files in monit.d
  tags: server,client,monit, common
  lineinfile:
    path: /etc/monitrc
    regexp: '^{{item}}'
    line: '{{item}}/*'
  loop:
    - 'include /etc/monit.d'
  notify: Restart monit

- name: Make sure monitrc exists and has right permissions
  tags: server,client,monit, common
  file:
    path: /etc/monitrc
    mode: 0600

- name: Make sure /etc/monit.d exists
  tags: server,client,monit, common
  file:
    path: /etc/monit.d
    state: directory

- name: Copying auxiliary scripts
  tags: server,client,monit, common
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
    mode: 0755
  loop:
    - usr/local/bin/monit_restart.sh
    - usr/local/bin/start_earlyoom.sh
    - usr/local/bin/stop_earlyoom.sh

- name: Adding monit to inittab to make it run always
  tags: server,client,monit, common
  lineinfile:
    path: /etc/inittab
    search_string: '{{item}}'
    line: '{{item}}'
  loop:
    - 'mo:2345:respawn:/usr/bin/monit -Ic /etc/monitrc'
  notify: Restart monit

- name: Copy config files
  tags: server,client,monit, common
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
    follow: yes
  loop:
    - etc/monit.d/common-monitrc
    - etc/monit.d/HPC-monitrc
  notify: Restart monit

- name: Activate monit service
  tags: server,client,monit, common
  file:
    path: /etc/rc.d/rc.monit
    mode: +x
  notify: Restart monit
