---
- name: Configuring a virtual box machine for teaching, with a live user and a shared folder, password is live
  hosts: "{{ variable_host | default('localhost') }}"
  gather_facts: false
  tasks:
  - name: Create user live with password live
    user:
      name: live
      groups: audio,cdrom,floppy,plugdev,video
      comment: "Live user for virtual machine"
      append: yes
      uid: 1000
      shell: /bin/bash
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa
      password: $6$6Y96BBbtb944m$g3BlMhPbkigLvjOKwrIyF2bIfYY.oF1yxKl90xsq4pR9ydGGG3AQ5RuZwOwOFx7HeBfuvmrEmrD.alYBYaBw51

  - name : Configure shell prompt with bashit
    block:
      - name: Clonning bashit
        git:
          repo: https://github.com/Bash-it/bash-it.git
          depth: 1
          dest: $HOME/.bash_it

      - name: Check if bashit is already installed
        lineinfile:
          path: $HOME/.bashrc
          line: 'source "$BASH_IT"/bash_it.sh'
          state: present
        register: bashitpresent

      - name: Installing bashit if not installed
        shell:
          cmd: $HOME/.bash_it/install.sh --silent
        when: bashitpresent.changed
    become: true
    become_user: live

  - name: Installing and configuring spack
    block:
      - name: Clonning spack
        git:
          repo: https://github.com/spack/spack.git
          dest: $HOME/repos/spack
      - name: Adding loading spack to bashrc
        lineinfile:
          path: $HOME/.bashrc
          regexp: '^{{ item }}'
          line: '{{ item }}'
        loop:
          - "source $HOME/repos/spack/share/spack/setup-env.sh"
    become: true
    become_user: live

  - name: Configuring doom emacs for live user
    block:
      - name: Copy the emacs install domm script
        copy:
          src: "{{item}}"
          dest: "/{{item}}"
          mode: +x
        loop:
          - usr/local/bin/install_and_setup_doom_emacs.sh
      - name: Run the install doom script
        shell:
          creates: $HOME/.doom.d
          cmd: /bin/bash /usr/local/bin/install_and_setup_doom_emacs.sh
    become: true
    become_user: live

  - name: Adding option to mount a shared resource onto /media/hd
    lineinfile:
      path: /etc/rc.d/rc.local
      search_string: '{{ item }}'
      line: '{{ item }}'
    loop:
      - "mount -t vboxsf -o rw,uid=1000,gid=1000 shared /media/hd 2>/dev/null"
