---
- name: Checking existence of installation directory
  tags: server,client,netdata
  stat:
    path: /opt/netdata
  register: netdatadir
  #failed_when: not netdatadir.stat.isdir

- name: Checking if netdata binary is installed in /opt
  tags: server,client,netdata
  stat:
    path: /opt/netdata/bin/netdata
  register: netdata
  #failed_when: not netdata.stat.exists

# wget -c https://github.com/netdata/netdata/releases/download/v1.38.0/netdata-x86_64-latest.gz.run -O /tmp/netdatainstall.sh
# echo y | bash /tmp/netdatainstall.sh'

- name: Downloading and installing netdata if not installed
  tags: netdata, client, server
  ansible.builtin.shell:
    cmd: |
      mv /usr/sbin/adduser{,-old};
      wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --non-interactive --auto-update ;
      mv /usr/sbin/adduser{-old,}
  when:
    netdatadir.stat.exists == false or netdata.stat.exists == false
  #environment:
  #  https_proxy: http:{{PROXY}}

# ## Removed proxy, not needed since late 2022
# # - name: Add proxy to netdata configuration
# #   lineinfile:
# #     dest: /opt/netdata/etc/netdata/netdata.conf
# #     regexp: '.*proxy = http://{{PROXY}}'
# #     line: '        proxy = http://{{PROXY}}'
# #     insertafter: '\[cloud\]'
# #   when:
# #     netdatadir.stat.exists and netdatadir.stat.isdir
# #   register: proxy

- name: Link netdata service to correct place
  tags: server,client,netdata
  file:
    src: /opt/netdata/system/netdata-init-d
    dest:  /etc/init.d/netdata-init-d
    state: link
  notify: Restart netdata

- name: Claim node
  tags: server,client,netdata
  shell:
    # cmd: '/opt/netdata/bin/netdata-claim.sh -token={{NETDATA_TOKEN}} -rooms={{NETDATA_ROOM}} -url=https://app.netdata.cloud -proxy={{PROXY}}'
    cmd: '/opt/netdata/bin/netdata-claim.sh -token={{NETDATA_TOKEN}} -rooms={{NETDATA_ROOM}} -url=https://app.netdata.cloud'
    creates: /opt/netdata/var/lib/netdata/cloud.d/claimed_id
  notify: Restart netdata
