---
- name: Check if firewall command is available
  tags: server,arno,firewall
  stat:
    path: /usr/sbin/arno-iptables-firewall
  register: arno

- name: Installing arno iptables if not installed
  tags: server,arno,firewall
  shell:
    cmd: source /root/.bashrc; sbopkg -B -k -i arno-iptables-firewall
  when:
    arno.stat.exists == False

- name: Copying firewall config template
  tags: server,arno,firewall
  template:
    src: '{{item}}.j2'
    dest: '/{{item}}'
    mode: o-rwx
  loop:
    - etc/arno-iptables-firewall/firewall.conf

- name: Copying firewall plugins config
  tags: server,arno,firewall
  template:
    src: '{{item}}'
    dest: '/{{item}}'
    #chmod: o-rwx
  loop:
    - etc/arno-iptables-firewall/plugins/ssh-brute-force-protection.conf
    - etc/arno-iptables-firewall/plugins/adaptive-ban.conf
  register: plugins

- name: Copying blocked hosts file
  tags: server,arno,firewall
  template:
    src: '{{item}}'
    dest: '/{{item}}'
  loop:
    - etc/arno-iptables-firewall/blocked-hosts
  register: blocked_hosts

- name: Copying conntrack file to increase max size
  tags: server,arno,firewall
  template:
    src: '{{item}}'
    dest: '/{{item}}'
  loop:
    - etc/arno-iptables-firewall/conf.d/conntrack.conf
  register: conntrack

- name: linking startup script
  tags: server,arno,firewall
  shell:
    cmd: ln -svf /etc/rc.d/rc.arno-iptables-firewall /etc/rc.d/rc.firewall
    creates: /etc/rc.d/rc.firewall

- name: Making arno startup script executable
  tags: server,arno,firewall
  file:
    path: /etc/rc.d/rc.arno-iptables-firewall
    mode: +x
  register: arnoexec

- name: Starting firewall if just made executable or added some config
  tags: server,arno,firewall
  shell: /etc/rc.d/rc.firewall restart
  when: arnoexec.changed == True or plugins.changed or blocked_hosts.changed or conntrack.changed
