---
- name: Check if firewall command is available
  stat:
    path: /usr/sbin/arno-iptables-firewall
  register: arno

- name: Installing arno iptables if not installed
  shell:
    cmd: source /root/.bashrc; sbopkg -B -k -i arno-iptables-firewall
  when:
    arno.stat.exists == False

- name: Copying firewall config
  template:
    src: '{{item}}.j2'
    dest: '/{{item}}'
    chmod: o-rwx
  loop:
    - etc/arno-iptables-firewall/firewall.conf

- name: linking startup script
  shell:
    cmd: ln -svf /etc/rc.d/rc.arno-iptables-firewall /etc/rc.d/rc.firewall
    creates: /etc/rc.d/rc.firewall

- name: Making arno startup script executable
  file:
    path: /etc/rc.d/rc.arno-iptables-firewall
    mode: +x
  register: arnoexec

- name: Activating ssh brute force protection
  replace:
    path: /etc/arno-iptables-firewall/plugins/ssh-brute-force-protection.conf
    regexp: "^ENABLED=0"
    replace: "ENABLED=1"
  register: sshenabled

- name: Adding ports for ssh protection
  replace:
    path: /etc/arno-iptables-firewall/plugins/ssh-brute-force-protection.conf
    regexp: '^SSH_BFP_PORTS=.*'
    replace: 'SSH_BFP_PORTS="22 443"'
  register: sshenabledports

- name: Setting up rate1 in ssh protection
  replace:
    path: /etc/arno-iptables-firewall/plugins/ssh-brute-force-protection.conf
    regexp: '^SSH_BFP_MAX_RATE1=.*'
    replace: 'SSH_BFP_MAX_RATE1="12"'
  register: sshenabledrate1

- name: Setting up rate2 in ssh protection
  replace:
    path: /etc/arno-iptables-firewall/plugins/ssh-brute-force-protection.conf
    regexp: '^SSH_BFP_MAX_RATE2=.*'
    replace: 'SSH_BFP_MAX_RATE2="20"'
  register: sshenabledrate2

- name: Activating adaptative ban
  replace:
    path: /etc/arno-iptables-firewall/plugins/adaptive-ban.conf
    regexp: "^ENABLED=0"
    replace: "ENABLED=1"
  register: adaptiveban

- name: Starting firewall if just made executable or added some config
  shell: /etc/rc.d/rc.firewall restart
  when: arnoexec.changed == True or adaptiveban.changed or sshenabled.changed or sshenabledports.changed or sshenabledrate1.changed or sshenabledrate2.changed
