---
- name: Copying templated config files
  tags: server,nis
  template:
    src: "{{item}}.j2"
    dest: "/{{item}}"
    backup: yes
  loop:
    - etc/yp.conf
    - etc/hosts.allow
    - etc/defaultdomain
  notify: Restart nis

- name: Copying Makefile config
  tags: server,nis
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
    backup: yes
  loop:
    - var/yp/Makefile 
  notify: Restart nis

- name: Enabling yp server
  tags: server,nis
  replace:
    dest: /etc/rc.d/rc.yp
    regexp: '^YP_SERVER_ENABLE=0'
    replace: 'YP_SERVER_ENABLE=1'
  notify: Restart nis

- name: Disabling yp client
  tags: server,nis
  replace:
    dest: /etc/rc.d/rc.yp
    regexp: '^YP_CLIENT_ENABLE=1'
    replace: 'YP_CLIENT_ENABLE=0'
  notify: Restart nis

- name: Make sure rc.yp is executable
  tags: server, nis
  ansible.builtin.file:
    path: /etc/rc.d/rc.yp
    mode: +x
  notify: Restart nis
