#+STARTUP: overview
This repository contains several scripts to build different kind of
tools that I have needed along time. The following describes the
structure and usage.
* =clonezilla=
   This shows how to clone a device into an image or how to clone and
   image to many computers. Maybe this could be scripted, I do not
   know how. It would be useful if the computers could be configured
   to boot from pxe by default and somehow clonezilla determines if
   the system needs to be reimaged.

   Working versions: 
   - clonezilla-live-2.6.4-10-amd64.iso
   - drbl-live-xfce-2.6.2-1-amd64.iso

* =computer-room=[0/1]
   This shows several scripts that can be used to configure either a
   client or a server for a computer room. 
   It is assumed that the system running this scripts is already in
   basic configured state (internet, etc).
   The services configured are
   |---------------------------------------+--------+--------|
   | service                               | client | server |
   |---------------------------------------+--------+--------|
   | fixed network ip interfaces           |        | X      |
   | dnsmasq                               |        | X      |
   | firewall                              |        | X      |
   | kanif                                 |        | X      |
   | nfs                                   | X      | X      |
   | nis                                   | X      | X      |
   | Network manager hook                  | X      |        |
   | ntp                                   | X      |        |
   | root internet access                  | X      | X      |
   | default session: xfce                 | X      |        |
   | latam keyboard                        | X      |        |
   | cronjob to check connection status    | X      |        |
   | Server public key for ssh access      | X      |        |
   | Remove permissions to halt / shutdown | X      |        |
   |---------------------------------------+--------+--------|

*** TODO Configure cronjobs for server [0/4]
    - [ ] kill_high_cpu
    - [ ] network.sh
    - [ ] sshserver.sh
    - [ ] wol.sh : needs mac list
* =configurations=
   This configures a clean install to give it a minimal working
   state. In principle, to configure slackware, you should run the
   following scripts:
   #+BEGIN_SRC sh
   bash configurations/config_slackware.sh
   bash packages/install_packages_slackware.sh # use COMPILE=yes if you want to compule the packages
   #+END_SRC
** OLD Lubuntu [9/11]
   - [X] Configure/install google remote desktop:
     https://support.google.com/chrome/answer/1649523?co=GENIE.Platform%3DDesktop&hl=en 
   - [X] Configure zerotier one : 
     - Install curl : sudo apt install curl
     - https://www.zerotier.com/download.shtml
     - Authorize the new computer
   - [X] Install syncthing:
     - https://apt.syncthing.net/
   - [ ] Install dropbox
     - https://www.dropbox.com/install-linux
   - [X] Inkscape : sudo apt install inkscape
   - [X] Libreoffice : sudo apt install libreoffice
   - [X] Texlive : sudo apt install texlive-full
   - [X] keepassxc : sudo apt install keepassxc
   - [X] obsproject : sudo apt install obsproject
   - [X] Openssh : sudo apt install openssh-server, configure port 443
   - [ ] emacs: sudo apt install emacs


* Onedrive, Google drive, etc in Linux 
** Slackware
*** One drive
    - Check : https://www.linuxuprising.com/2018/07/how-to-mount-onedrive-in-linux-using.html
    - Mount command : rclone  --vfs-cache-mode writes mount remote-onedrive: ~/OneDrive/ --daemon 
*** Google Drive
    - Check :
      http://thiagopirola.blogspot.com/2016/07/google-drive-in-slackware-14x.html
    - Mount command : rclone  --vfs-cache-mode writes mount
      remote-googledrive: ~/Google\ Drive/ --daemon 
      
* =liveslak=
   This allows to create a custom =liveslak= image. This scripts are
   assumed to run on a slackware 14.2 box (to use updated tools, but
   the live usb is based on an already downloaded liveslack).

   Description:
   - =make_extra_modules.sh= :: creates extramodules like
        =miniconda3=, =valgrind=, =paraview=, =openmpi= .  
   - =create_custom_liveslack_iso.sh= :: This creates the actual
        liveslack iso using the custom modules. 

   Please read the file =live-distro.org= .  
* =packages= [0/2] 
   Allows to install several packages defined inside each
   script. Specific cases, like anaconda or firefox, are handled with
   their own scripts. Please put here any package you want to
   install. 
** TODO Check installation of heaptrack
  [[https://github.com/KDE/heaptrack]]
  
** TODO Check slackroll
   https://rg3.github.io/slackroll/
* =vagrant-machines=
   Here are several examples to create either a basebox and some
   vagrantfiles .  

* packer
  Here I put some scripts to automate slackware installation. Strongly
  inspired on https://github.com/akosiaris/packer-slackware/ , adapted
  for slackware current. 
* TOCHECK 
  - https://github.com/bifferos/explodeinstaller
  - https://github.com/akosiaris/packer-slackware/blob/master/slackware64-14.2.json
  - https://github.com/Cyclenerd/postinstall/blob/master/postinstall.sh
* FIXES
** tab not working on remote x2go connection with xfce4
This happens in the console and is due to a changing window shortcut that msut
be removed. The fis is
- Open =~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml=
- Replace ~<property name="&lt;Super&gt;Tab" type="string"
  value="switch_window_key"/>~ with ~<property name="&lt;Super&gt;Tab"
  type="empty"/>~
REFS:
- https://www.smork.info/blog/2015/06/10/fixing_bash_tab_completion_in_xfce.html
- https://stackoverflow.com/questions/23418831/command-line-auto-complete-tab-key-not-work-in-terminal-for-ubuntu
-
** virtualbox gui dying with glib error
Run
#+begin_src shell
VBoxManage setextradata global GUI/UpdateDate never
#+end_src
REF: https://www.linuxquestions.org/questions/slackware-14/cannot-register-existing-type-%27nmagentmanagererror%27-4175690823/
* NOTES
** Remote x11 connection with opengl hardware acceleration
- Server config
  #+begin_src conf
  edit /etc/X11/Xwrapper.config
  and add allowed_users = anybody
  #+end_src
- Server run
  #+begin_src shell
  startx -- :1
  x11vnc  --display :1
  #+end_src
- on client: turbovnc, then maybe change resolution with
  #+begin_src shell
  xrandr --fb 1280x700
  #+end_src

** Resizing or creating a new partition
I will use sgdisk to resize the last partition
#+begin_src shell
# move backup partition to the end of disk
sgdisk -e /dev/sda
# delete and recreate last partition (assumed to be number 6)
sgdisk -d 6 /dev/sda
sgdisk -N 6 /dev/sda
# update partition table, if unsuscessfull, reboot
partprobe /dev/sda
# resize partition
resize2fs /dev/sda6
#+end_src
REF: https://superuser.com/questions/660309/live-resize-of-a-gpt-partition-on-linux

** Enabling quota on ext4
REF: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/assembly_limiting-storage-space-usage-on-ext4-with-quotas_managing-file-systems
#+begin_src shell
umount -l /home; tune2fs -O quota /dev/sdb2; tune2fs -Q usrquota /dev/sdb2; mount /home
#+end_src
* PACKAGES
  - https://spack-tutorial.readthedocs.io/en/latest/tutorial_modules.html
  - https://researchit.las.iastate.edu/spack-based-software-modules
  - https://spack.readthedocs.io/en/latest/
