---
- name: Commenting local home mounting (maybe check for nvme also)
  tags: client,nfs
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '(^/dev/sd.*/home.*ext4.*)' # uses a group
    line: '# \1' # uses the group capture
    backup: yes
    backrefs: yes

- name: Adding mount of nfs /home (from server) 
  tags: client,nfs
  ansible.posix.mount:
    path: "{{item.path}}"
    src: "{{SERVERIP}}:/home"
    fstype: nfs
    #opts: rw,soft,intr,usrquota
    #opts: defaults,rw,soft,rsize=1048576,wsize=1048576,vers=3,nointr,timeo=10,actimeo=60,nolock,tcp
    #opts: defaults,rw,soft,nolock
    opts: nfsvers=4.2,rw,soft,nolock
    state: "{{item.action}}"
  loop:
    - { path: /home, action: present } # adds to fstab
    - { path: /home, action: mounted }
  notify: Restart nfs

- name: Puting initial nfs mounting into background since it corresponds to non-essential fs
  tags: client,nfs
  replace:
    path: /etc/rc.d/rc.inet2
    backup: yes
    regexp:  ' /sbin/mount -a -t nfs          # This may be our /usr runtime!'
    replace: ' /sbin/mount -a -t nfs &         # This may be our /usr runtime!'
  notify: Restart nfs

- name: Removing sync from rc.6 since it blocks restart when nfs server is stalled
  tags: client,nfs
  replace:
    path: /etc/rc.d/rc.6
    backup: yes
    regexp:  "^{{ item }}"
    replace: "#{{ item }}"
  loop:
    - /bin/sync
    - wait
  notify: Restart nfs

# - name: Adding timeout to nfs umount and sync when restarting to avoid hanging after a stalled nfs server
#   tags: client,nfs
#   ansible.builtin.copy:
#     src: "{{ item }}"
#     dest: "/{{ item }}"
#     owner: root
#     group: root
#     backup: yes
#   loop:
#     - etc/rc.d/rc.6
#   notify: Restart nfs
