---
- name: Adding nfs home mount
  tags: nfs
  lineinfile:
    dest: /etc/fstab
    regexp: '^{{SERVERIP}}:/home'
    line: '{{SERVERIP}}:/home  /home  nfs  rw,hard,intr,usrquota  0  0'
    backup: yes
  notify: Restart nfs

- name: Puting initial nfs mounting into background since it corresponds to non-essential fs
  tags: nfs
  replace:
    path: /etc/rc.d/rc.inet2
    backup: yes
    regexp:  ' /sbin/mount -a -t nfs          # This may be our /usr runtime!'
    replace: ' /sbin/mount -a -t nfs &         # This may be our /usr runtime!'
  notify: Restart nfs
