---
- name: Adding nfs home mount
  lineinfile:
    dest: /etc/fstab
    regexp: '^{{SERVERIP}}:/home'
    line: '{{SERVERIP}}:/home  /home  nfs  rw,hard,intr,usrquota  0  0'
    backup: yes
  register: fstab

- name: Puting initial nfs mounting into background since it corresponds to non-essential fs
  replace:
    path: /etc/rc.d/rc.inet2
    backup: yes
    regexp:  ' /sbin/mount -a -t nfs          # This may be our /usr runtime!'
    replace: ' /sbin/mount -a -t nfs &         # This may be our /usr runtime!'
  register: nfsbg
  
- name: Restarting service if needed
  shell:
    cmd: '/etc/rc.d/rc.{{item}} restart'
  loop:
    - nfsd
    - inet2
  when:
    fstab.changed or nfsbg.changed
    
