---
- name: Adding nfs home mount
  tags: client,nfs
  lineinfile:
    dest: /etc/fstab
    regexp: '^{{SERVERIP}}:/home'
    line: '{{SERVERIP}}:/home  /home  nfs  rw,hard,intr,usrquota  0  0'
    backup: yes
  notify: Restart nfs

- name: Puting initial nfs mounting into background since it corresponds to non-essential fs
  tags: client,nfs
  replace:
    path: /etc/rc.d/rc.inet2
    backup: yes
    regexp:  ' /sbin/mount -a -t nfs          # This may be our /usr runtime!'
    replace: ' /sbin/mount -a -t nfs &         # This may be our /usr runtime!'
  notify: Restart nfs

- name: Adding timeout to nfs umount when restarting to avoid hanging after a stalled nfs server
  tags: client,nfs
  replace:
    path: /etc/rc.d/rc.6
    backup: yes
    regexp:  '/bin/umount -v -a -l -f -r -t nfs,nfs4,smbfs,cifs '
    replace: '/usr/bin/timeout 10s /bin/umount -v -a -l -f -r -t nfs,nfs4,smbfs,cifs '
  notify: Restart nfs
