---
- name: Check if sshguard is installed
  stat:
    path: /usr/sbin/sshguard
  register: sshguard

- name: Installing sshguard if not installed
  shell:
    cmd: sbopkg -B -k -i sshguard
  when:
    sshguard.stat.exists == False

- name: Copying sshguard config
  tags: server,sshguard
  ansible.builtin.copy:
    src: etc/sshguard.conf
    dest: /etc/sshguard.conf
    backup: yes
  notify: Restart sshguard

