---
- name: Configure virtual machine live user and shared folder
  hosts: all
  vars:
    network_available: true    
  tasks:
  - name: Add live user is present (password is live)
    user:
      name: live
      comment: "Live User"
      home: /home/live
      groups: audio,cdrom,floppy,plugdev,video
      append: yes
      shell: /bin/bash
      uid: 1000
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa
      password: $6$6Y96BBbtb944m$g3BlMhPbkigLvjOKwrIyF2bIfYY.oF1yxKl90xsq4pR9ydGGG3AQ5RuZwOwOFx7HeBfuvmrEmrD.alYBYaBw51

  - name: Configuring bashit
    block: 
      - name: Cloning bashit for live user
        git:
          repo: https://github.com/Bash-it/bash-it.git
          dest: $HOME/.bash_it
      - name: Install bashit (NOT IDEMPOTENT)
        shell:
          cmd: '$HOME/.bash_it/install.sh --silent'
    become: true
    become_user: live

  - name: Install and configure spack
    block:
      - name: Clonning spack repo
        git:
          repo: https://github.com/spack/spack
          dest: $HOME/repos/spack
      - name: Adding spack env setting to .bashrc
        lineinfile:
          dest: $HOME/.bashrc
          regexp: '^{{item}}'
          line: '{{item}}'
        loop:
          - 'source $HOME/repos/spack/share/spack/setup-env.sh'
    become: true
    become_user: live

  - name: Configuring doom emacs for live user
    block:
      - name: Copy the emacs install domm script
        copy:
          src: "{{item}}"
          dest: "/{{item}}"
          mode: +x
        loop:
          - usr/local/bin/install_and_setup_doom_emacs.sh
      - name: Run the install doom script
        shell:
          creates: $HOME/.doom.d
          cmd: /bin/bash /usr/local/bin/install_and_setup_doom_emacs.sh
    become: true
    become_user: live

  - name: Add mounting of shared media
    lineinfile:
      dest: /etc/rc.d/rc/.local
      search_string: '{{item}}'
      line: '{{item}}'
    loop:
      - 'mount -t vboxsf -o rw,uid=1000,gid=1000 shared /media/hd 2>/dev/null'

