---
- name: Copy config files
  tags: server,monit
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
    follow: yes
  loop:
    - etc/monit.d/SERVER-monitrc
    - etc/monit.d/tailscale
    - etc/monit.d/sshguard
  register: monitfiles

- name: Activate monit service
  tags: server,monit
  file:
    path: /etc/rc.d/rc.monit
    mode: +x
  register: monitservice
  
- name: Restart monit if any changed detected
  tags: server,monit
  command:
    cmd: /etc/rc.d/rc.monit restart
  when:
    monitfiles.changed or monitservice.changed
