---
- name: Check if monit is installed
  stat:
    path: /usr/bin/monit
  register: monit

- name: Installing monit if not installed
  shell:
    cmd: source /root/.bashrc; sbopkg -B -k -i monit
  when:
    monit.stat.exists == False

- name: Adding option to read files in monit.d
  lineinfile:
    path: /etc/monitrc
    regexp: '^{{item}}'
    line: '{{item}}/*'
  loop:
    - 'include /etc/monit.d'

- name: Copy config files
  tags: server,monit
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
    follow: yes
  loop:
    - etc/monit.d/tailscale
    - etc/monit.d/sshguard
  notify: Restart monit

- name: Copy templated config files
  tags: server,monit
  template:
    src: "{{item}}.j2"
    dest: "/{{item}}"
    follow: yes
  loop:
    - etc/monit.d/SERVER-monitrc
  notify: Restart monit

- name: Activate monit service
  tags: server,monit
  file:
    path: /etc/rc.d/rc.monit
    mode: +x
  notify: Restart monit
  
