---
- hosts: "{{ variable_host | default('server') }}"
  gather_facts: false
  vars:
    network_available: true
  vars_files:
    - vars/main.yml
    - passwords.yml
  roles:
    - ../common/roles/proxy
    - ../common/roles/shutdownperms
    - quota
    - network
    - dnsmasq
    - firewall
    - nfs
    - sshd
    - nis
    - crontab
    - ../common/roles/monit
    - monit
    - cntlm
    - clustershell
    - x2go
    - etcskel
    - ../common/roles/ganglia
    - ganglia
    - apache
    - ../common/roles/wakeonlan
    - ../common/roles/netdata
    - tailscale
