---
- name: Removing permissions to shudown or halt system
  tags: server,client,shutdownperms
  file:
    dest: "{{item}}"
    mode: o-x
  loop:
    - /sbin/shutdown
    - /sbin/halt

- name: Copying polkit rules and acpi handler
  tags: server,client,shutdownperms
  copy: 
    src: "{{item}}"
    dest: "/{{item}}"
    backup: yes
  loop:
    - etc/polkit-1/rules.d/disallow-power-options.rules
    - etc/acpi/acpi_handler.sh
    - etc/acpi/events/powerbutton

# NOTE: This might not work and editing /etc/sddm.conf might be needed
- name: Creating file in /etc/sddm.conf.d to disable shutdown and poweroff
  tags: server,client,shutdownperms
  copy:
    src: etc/sddm.conf.d/00-disable-shutdown-poweroff.conf
    dest: /etc/sddm.conf.d/00-disable-shutdown-poweroff.conf
    backup: no
  register: sddm_conf

- name: restartinf sddm if needed
  tags: server,client,shutdownperms
  service:
    name: sddm
    state: restarted
  when: sddm_conf.changed