---
- name: Removing permissions to shudown or halt system
  tags: server,client,shutdownperms
  file:
    dest: "{{item}}"
    mode: o-x
  loop:
    - /sbin/shutdown
    - /sbin/halt

- name: Copying polkit rules and acpi handler
  tags: server,client,shutdownperms
  copy: 
    src: "{{item}}"
    dest: "/{{item}}"
    backup: yes
  loop:
    - etc/polkit-1/rules.d/disallow-power-options.rules
    - etc/acpi/acpi_handler.sh
