---
- name: Basic slackware configuration after installation
  hosts: "{{ all | default('clients') }}"
  gather_facts: false
  vars:
    network_available: true
  tasks:
  - name: Default init to runlevel 4
    replace:
      dest: /etc/inittab
      regexp: '^id:3:initdefault'
      replace: 'id:4:initdefault'
      backup: yes

  - name: Activating nfs and ssh services
    file:
      path: '/etc/rc.d/rc.{{item}}'
      mode: +x
    loop:
      - nfsd
      - sshd

  - name: Configuring time zone to bogota
    file:
      src: /usr/share/zoneinfo/America/Bogota
      dest: /etc/localtime
      force: yes
      state: link

  - name: Adding more ntp servers
    blockinfile:
      dest: /etc/ntp.conf
      backup: yes
      block: |
        server   0.pool.ntp.org   iburst
        server   0.co.pool.ntp.org   iburst
    register:
      ntpservers

  - name: Activating ntp service
    file:
      path: /etc/rc.d/rc.ntpd
      mode: +x
    register: ntpservice
 
  - name: Restarting ntpd if needed
    shell:
      cmd: /etc/rc.d/rc.ntpd restart
    when:
      ntpservers.changed or ntpservice.changed

  - name: Touching .bashrc file in root
    file:
      path: /root/.bashrc
      state: touch
      modification_time: preserve
      access_time: preserve

  - name: Wake on lan
    debug:
      msg: "Ignoring Wake on lan settings for now"

  - name: Configuring slackpkg
    block:
      - name: Configuring slackpkg options
        replace:
          dest: /etc/slackpkg/slackpkg.conf
          regexp: '^{{item.key}}'
          replace: '{{item.value}}'
          backup: yes
        loop:
          - { key: "DIALOG=on", value: "DIALOG=off" }
          - { key: "BATCH=off", value: "BATCH=on" }
          - { key: "DEFAULT_ANSWER=n", value: "DEFAULT_ANSWER=y" }
          - { key: "WGETFLAGS=.*", value: "WGETFLAGS=--passive-ftp" }
        register: slackpkgconf

      - name: Configure slackpkg mirrors
        lineinfile:
          dest: /etc/slackpkg/mirrors
          regexp: '^{{item}}'
          line: '{{item}}'
        loop:
          - http://mirrors.slackware.com/slackware/slackware64-current/
        register: mirrors

      - name: Configuring slackpkg blacklist
        lineinfile:
          path: /etc/slackpkg/blacklist
          regexp: '^{{item}}'
          line: '{{item}}'
          backup: yes
        loop:
          - 'kernel-generic.*'
          - 'kernel-huge.*'
          - 'kernel-modules.*'
          - 'kernel-source.*'
          - 'kernel-headers.*'
          - '[0-9]+_SBo'
          - '[0-9]+alien'
        register: blacklist

      - name: Updating slackpkg if needed
        shell:
          cmd: '{{item}}'
        loop:
          - 'source $HOME/.bashrc; echo YES | slackpkg -batch=on -default_answer=y update gpg'
          - 'source $HOME/.bashrc; slackpkg -batch=on -default_answer=y update'
        when:
          mirrors.changed or blacklist.changed or slackpkgconf.changed

  - name: Adding dhcp on both eth0 and eth1
    replace:
      dest: /etc/rc.d/rc.inet1.conf
      regexp: '^USE_DHCP\[{{item}}\]="(no)?"'
      replace: 'USE_DHCP[{{item}}]="yes"'
    loop:
      - 0
      - 1

  - name: Activating networkmanager service
    file:
      path: /etc/rc.d/rc.networkmanager
      mode: +x
    register: nmservice

  - name: restart networkmanager service if needed
    shell:
      cmd: /etc/rc.d/rc.networkmanager
    when:
      nmservice.changed

  - name: Configuring lilo
    block: 
      - name: Check if lilo.conf exists
        stat:
          path: /etc/lilo.conf
        register: lilo

      - name: Decreasing lilo time
        replace:
          dest: /etc/lilo.conf
          regexp: '^timeout.*'
          replace: 'timeout = 50'
          backup: yes
        when:
          lilo.stat.exists
        register: lilofile

      - name: Running lilo if updated
        shell:
          cmd: '/sbin/lilo &>/dev/null'
        when:
          lilofile.changed

  - name: Configuring slpkg
    block:
      - name: Checking if slpkg is installed
        stat:
          path: /usr/bin/slpkg
        register: slpkg

      # - name: Installing urllib3 (if used for slpkg, it does not create /etc/ files)
      #   pip:
      #     name: '{{ item }}'
      #     executable: pip3
      #   loop:
      #     - urllib3
      #   register: slpkginstalled

      # - name: Installing slpkg if needed
      #   shell:
      #     cmd: 'source /root/.bashrc; cd /tmp; wget https://gitlab.com/dslackw/slpkg/-/archive/3.9.3/slpkg-3.9.3.tar.gz; tar xf slpkg-3.9.3.tar.gz; cd slpkg-3.9.3; ./install.sh; '
      #   when:
      #     slpkg.stat.exists == False
      #   register: slpkginstalled

      # - name: Configuring slpkg options
      #   replace:
      #     dest: /etc/slpkg/slpkg.toml
      #     regexp: '^{{item.key}}'
      #     replace: '{{item.value}}'
      #     backup: yes
      #   loop:
      #     #- { key: "RELEASE=stable", value: "RELEASE=current" }
      #     #- { key: "DEFAULT_ANSWER=n", value: "DEFAULT_ANSWER=y" }
      #     #- { key: "DOWNDER_OPTIONS=.*", value: "DOWNDER_OPTIONS=-N --no-check-certificate" }
      #     #- { key: "NOT_DOWNGRADE=off", value: "NOT_DOWNGRADE=on" }
      #   register: slpkgopts

      - name: Configuring slpkg repos
        replace:
          path: /etc/slpkg/repositories.toml
          backup: yes
          regexp: '(\[{{ item }}\]\nENABLE =) false'
          replace: '\1 true'
        loop:
          - SLACK
          - SLACK_EXTRA
          - SLACK_PATCHES
          - ALIEN
        register: slpkgrepos
        

      - name: Deactivate SBO
        replace:
          path: /etc/slpkg/repositories.toml
          backup: yes
          regexp: '(\[{{ item }}\]\nENABLE =) true'
          replace: '\1 false'
        loop:
          - SBO


      - name: Make slack the default repo
        ansible.builtin.replace:
          path: /etc/slpkg/repositories.toml
          regexp: '^REPOSITORY = .*'
          replace: 'REPOSITORY = "slack"'
          

      - name: Replace all -15.0 with -current
        ansible.builtin.replace:
          path: /etc/slpkg/repositories.toml
          regexp: '-15\.0'
          replace: '-current'
          

      - name: Configuring slpkg blacklist
        replace:
          path: /etc/slpkg/blacklist.toml
          regexp: '^PACKAGES.*'
          replace: 'PACKAGES = ["kernel-*"]'
          backup: yes
        register: slpkgblacklist

      # - name: Copy patched file_size using urllib3
      #   copy:
      #     src: '{{item}}'
      #     dest: '/{{item}}'
      #     backup: yes
      #   loop:
      #     - 'usr/lib64/python3.9/site-packages/slpkg/file_size.py'
      #   register: urllib3

      - name: Updating slpkg if needed
        shell:
          cmd: 'source $HOME/.bashrc; slpkg update'
        when :
          slpkgrepos.changed or slpkgblacklist.changed 


  - name: Configuring sbopkg
    block:
      - name: Checking if sbopkg is installed
        stat:
          path: /usr/sbin/sbopkg
        register: sbopkg

      - name: Installing sbopkg if not installed
        shell:
          cmd: 'wget https://github.com/sbopkg/sbopkg/releases/download/0.38.2/sbopkg-0.38.2-noarch-1_wsr.tgz; upgradepkg --install-new  sbopkg-0.38.2-noarch-1_wsr.tgz'
        when:
          sbopkg.stat.exists == False
        register: sbopkginstalled

      - name: Configuring sbopkg for slackware current
        replace:
          dest: /etc/sbopkg/sbopkg.conf
          regexp: '{{item.key}}'
          replace: '{{item.value}}'
          backup: yes
        loop:
          - {key: "REPO_BRANCH:-15.0", value: "REPO_BRANCH:-current"}
          - {key: "REPO_NAME:-SBo}", value: "REPO_NAME:-SBo-git}"}
        register: sbopkgcurrent

      - name: Creating needed directories
        file:
          path: '{{item}}'
          state: directory
        loop:
          - /var/lib/sbopkg/SBo/14.2
          - /var/lib/sbopkg/SBo/15.0
          - /var/log/sbopkg
          - /var/lib/sbopkg/queues
          - /var/cache/sbopkg
          - /tmp/SBo
        register: sbopkgdirs  

      - name: Updating sbopkg if needed
        shell:
          cmd: 'source $HOME/.bashrc; sbopkg -r -V SBo-git/current'
        when:
          sbopkg.stat.exists == False or sbopkginstalled.changed or sbopkgcurrent.changed or sbopkgdirs.changed

  - name: Configuring dhcpcd client to use clientid instead of duid
    replace:
      dest: /etc/dhcpcd.conf
      regexp: '{{item.key}}'
      replace: '{{item.value}}'
      backup: yes
    loop:
      - {key: "^#clientid", value: "clientid"}
      - {key: "^duid", value: "#duid"}

  - name: Creaating config for virtual monitor
    copy:
      dest: /etc/X11/xorg.conf.d/11-monitor.conf
      content: |
         Section "Monitor"
         Identifier "Virtual1"
         Option "PreferredMode" "1680x1050"
         EndSection

  - name: Added loading of /etc/profile to bashrc skeleton
    lineinfile:
      dest: /etc/skel/.bashrc
      regexp: '^{{item}}'
      line: '{{item}}'
      create: yes
    loop:
      - 'source /etc/profile'

  - name: Fixing xinitrc on etc skel
    copy:
      src: /etc/xdg/xfce4/xinitrc
      dest: /etc/skel/.xinitrc
      mode: +x

  - name: Copying xsession to etc skel
    copy:
      src: /etc/xdg/xfce4/xinitrc
      dest: /etc/skel/.xsession
      mode: +x

  - name: Creating Xauthority
    file:
      path: /etc/skel/.Xauthority
      state: touch
      access_time: preserve
      modification_time: preserve

  - name: Configuring latam keyboard
    blockinfile:
      dest: /etc/X11/xorg.conf.d/90-keyboard-layout.conf
      create: yes
      block: |
        Section "InputClass"
          Identifier "keyboard defaults"
          MatchIsKeyboard "on"
          #MatchDevicePath "/dev/input/event*"
          #Driver "evdev"
          Option "XkbLayout" "latam,us"
          #Option "XkbVariant" ""
          Option "XkbOptions" "terminate:ctrl_alt_bksp"
        EndSection

  - name: Configure fonts (TO IMPROVE)
    shell:
      cmd: '{{item.command}}'
      creates: '{{item.file}}'
    loop:
      - {command: 'mkfontscale /usr/share/fonts/100dpi', file: '/usr/share/fonts/100dpi/fonts.scale'}
      - {command: 'mkfontdir /usr/share/fonts/100dpi', file: '/usr/share/fonts/100dpi/fonts.dir'}
      # The commands 'xset +fp /usr/share/fonts/100dpi; xset fp rehash' require display

  # To automate the dialog in curses, tmux is used
  # REF: https://superuser.com/questions/585398/sending-simulated-keystrokes-in-bas
  - name: Check if link to xfce exists
    stat:
      path: /etc/X11/xinit/xinitrc
    register: xinitrclink

  - name: Configuring xwmconfig 
    shell:
      cmd: 'tmux new-session -d -t Test; tmux send-keys -t Test: "xwmconfig" "Enter" ; tmux send-keys -t Test: "Down" "Enter"; tmux kill-session -t Test'
    when:
      xinitrclink.stat.lnk_source != '/etc/X11/xinit/xinitrc.xfce'


  - name: Setting generic hostname to later use the one from dhcpc
    copy:
      dest: /etc/HOSTNAME
      content: | 
        localhost

  # - name: making xdm first option in rc.4 
  #   copy:
  #     dest: /etc/rc.d/rc.4.local
  #     content: | 
  #       if [ -x /usr/bin/xdm ]; then exec /usr/bin/xdm -nodaemon; elif [ -x /usr/X11R6/bin/xdm ]; then exec /usr/X11R6/bin/xdm -nodaemon; fi
  #     mode: +x

  - name: Checking if system has efi boot files
    stat:
      path: /boot/efi/EFI/Slackware
    register: efi

  - name: Fixing efi boot on some hewlet packard bios -> create needed dir
    copy:
      src: /boot/efi/EFI/Slackware/
      dest: /boot/efi/EFI/boot/
      remote_src: yes
      directory_mode: yes
    when: efi.stat.exists

  - name: Checking if new efi directory was created
    stat:
      path: /boot/efi/EFI/boot/
    register: efiboot

  - name: Fixing efi boot on some hewlet packard bios -> changing names
    copy:
      src: /boot/efi/EFI/boot/elilo.efi
      dest: /boot/efi/EFI/boot/bootx64.efi
      remote_src: yes
    when:
      efiboot.stat.exists
