- name: Creating local scratch dir
  tags: client,harddisk
  file:
    path: /mnt/scratch
    state: directory

- name: "Reading device information: /dev/sda"
  tags: client,harddisk
  parted:
    device: "/dev/sda"
    unit: MiB
  register: device_info

# # - name: "Print info2"
# #   debug:
# #     msg: "{{ item.num }}"
# #   loop: "{{ device_info.partitions }}"

- name: "Adding new partition /dev/sda7"
  tags: client,harddisk
  parted:
    device: "/dev/sda"
    number: "7"
    part_type: primary
    state: present
    part_end: "100%"
    part_start: "{{ device_info.partitions[5].end + 0}}MiB"
    align: undefined
    fs_type: ext4
    label: gpt

- name: "Format /dev/sda7 with ext4"
  tags: client,harddisk
  filesystem:
    dev: "/dev/sda7"
    fstype: ext4

- name: Mounting /dev/sda7 onto /mnt/scratch
  tags: client,harddisk
  ansible.posix.mount:
    path: "{{item.path}}"
    src: /dev/sda7
    fstype: ext4
    state: "{{item.action}}"
  loop:
    - { path: /mnt/scratch, action: present } # adds to fstab
    - { path: /mnt/scratch, action: mounted }
  register: mount
