---
- name: Activating needing services
  tags: client,nis
  file:
    path: '/etc/rc.d/rc.{{item}}'
    mode: +x
  loop:
    - nfsd
    - yp
  notify: Restart nis

- name: Writing nisdomain to configfile
  tags: client,nis
  lineinfile:
    dest: /etc/defaultdomain
    regexp: '^{{NISDOMAIN}}'
    line: '{{NISDOMAIN}}'
    backup: yes
    create: yes
  notify: Restart nis

- name: Adding setting defultdomain at startup
  tags: client,nis
  lineinfile:
    dest: /etc/rc.d/rc.local
    regexp: '^{{item}}'
    line: '{{item}}'
    backup: yes
  loop:
    - 'nisdomainname -F /etc/defaultdomain'
  notify: Restart nis

- name: Removing typo line with  defultdomain at startup
  tags: client,nis
  lineinfile:
    dest: /etc/rc.d/rc.local
    regexp: '^{{item}}'
    line: '{{item}}'
    state: absent
  loop:
    - 'nisdomainame -F /etc/defaultdomain'

- name: Adding yp server config
  tags: client,nis
  lineinfile:
    dest: /etc/yp.conf
    regexp: '^{{item}}'
    line: '{{item}}'
    backup: yes
  loop:
    - 'ypserver {{SERVERIP}}'
  notify: Restart nis

- name: Copying nsswitch config
  tags: client,nis
  copy:
    src: '{{item}}'
    dest: '/{{item}}'
    backup: yes
  loop:
    - etc/nsswitch.conf
  notify: Restart nis

- name: Adding needed pattern to /etc/passwd
  tags: client,nis
  lineinfile:
    dest: /etc/passwd
    search_string: '{{item}}'
    line: '{{item}}'
    backup: yes
  loop:
    - '+::::::'
  notify: Restart nis
  
- name: Adding needed pattern to /etc/shadow
  tags: client,nis
  lineinfile:
    dest: /etc/shadow
    search_string: '{{item}}'
    line: '{{item}}'
    backup: yes
  loop:
    - '+::::::::'
  notify: Restart nis

- name: Adding needed pattern to /etc/group
  tags: client,nis
  lineinfile:
    dest: /etc/group
    search_string: '{{item}}'
    line: '{{item}}'
    backup: yes
  loop:
    - '+:::'
  notify: Restart nis

- name: Disabling yp server
  tags: client,nis
  replace:
    dest: /etc/rc.d/rc.yp
    regexp: '^YP_SERVER_ENABLE=1'
    replace: '^YP_SERVER_ENABLE=0'
    backup: yes
  notify: Restart nis

- name: Enabling yp client
  tags: client,nis
  replace:
    dest: /etc/rc.d/rc.yp
    regexp: '^YP_CLIENT_ENABLE=0'
    replace: '^YP_CLIENT_ENABLE=1'
    backup: yes
  notify: Restart nis

- name: Remove broadcast option in yp
  tags: client,nis
  lineinfile:
    dest: /etc/default/yp
    regexp: '{{item}}'
    line: '{{item}}'
  loop:
    - 'YPBIND_OPTS=" "'
  notify: Restart nis
