---
- name: Verify that x2godbadmin is available
  tags: client,x2go
  stat:
    path: /usr/sbin/x2godbadmin
  register: x2godbadmin
  #failed_when: not x2godbadmin.stat.exists

# Commented out since installation is better done under the packages script
- name: Installing x2go if not installed
  tags: client,x2go
  shell:
    cmd: source /root/.bashrc; sqg -p x2goserver; MAKEFLAGS=-j$(nproc)  printf "Q\n" | sbopkg -B -k -i x2goserver
  when:
    x2godbadmin.stat.exists == false
  notify: Restart x2goserver


- name: Activating x2goserver on client
  tags: client,x2go
  file:
    path: /etc/rc.d/rc.x2goserver
    mode: +x
  register: service
  notify:
    - Restart x2goserver

- name: Create x2go database
  tags: client,x2go
  shell:
    cmd: /usr/sbin/x2godbadmin --createdb
    creates: /var/lib/x2go/x2go_sessions
  when:
    service.changed or x2godbadmin.changed or x2godbadmin.stat.exists
  notify:
    - Restart x2goserver

- name: Copying script to clean sessions
  tags: client,x2go
  copy:
    src: usr/local/bin/clean_x2go_oldsessions.sh
    dest: /usr/local/bin/clean_x2go_oldsessions.sh
    mode: '0755'

- name: Add cron job to run the cleaning session script every hour
  tags: client,x2go
  cron:
    name: "Run script every hour to clean x2gosessions"
    minute: "0"
    hour: "*"
    job: "/usr/local/bin/clean_x2go_oldsessions.sh"


- name: Fixing x2go compositing by removing it from xfce with x2go
  tags: client,x2go
  block:
    - name: Adding x2go config file (must be executable). See "https://gitlab.xfce.org/xfce/xfwm4/-/issues/551"
      lineinfile:
        path: /etc/x2go/xinitrc.d/xfwm4_no_compositing
        create: true
        mode: +x
        state: present
        search_string: '{{item}}'
        line: '{{item}}'
      loop:
        - "/usr/bin/xfconf-query -c xfwm4 -p /general/use_compositing -s false"

    - name: Global disabling of xfce compositing . See "https://bugzilla.redhat.com/show_bug.cgi?id=1954754"
      blockinfile:
        path: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
        create: yes
        block: |
          <?xml version="1.0" encoding="UTF-8"?>

          <channel name="xfwm4" version="1.0">
            <property name="general" type="empty">
            <property name="use_compositing" type="bool" value="false"/>
            </property>
          </channel>

