- name: Copy config files
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
    follow: yes
  loop:
    - etc/monit.d/CLIENT-monitrc
  register: monitfiles

- name: Activate monit service
  file:
    path: /etc/rc.d/rc.monit
    mode: +x
  register: monitservice

- name: Restart monit if any changed detected
  command:
    cmd: /etc/rc.d/rc.monit restart
  when:
    monitfiles.changed or monitservice.changed
