---
- name: Adding minute_maintenance job
  cron:
    name: "Run useful script every minute"
    minute: "*/1"
    job: "/bin/bash /root/repos/computer-labs/computer-room/files/CLIENT-cron/check_status.sh &>/var/log/minute_maintenance.log"
  register: minute

- name: Restart service in config changed
  command:
    cmd: /etc/rc.d/rc.crond restart
  when:
    minute.changed 
