---
- name: Activating ntpd service
  file:
    path: /etc/rc.d/rc.ntpd
    mode: +x
  register: ntpd

# - name: Copying ntp config from template
#   template:
#     src: '{{item}}.j2'
#     dest: '/{{item}}'
#     backup: yes
#   loop:
#     - etc/ntp.conf
#   register: config
- name: Adding ntp config , line by line
  lineinfile:
    dest: /etc/ntp.conf
    search_string: '^{{item}}'
    line: '{{item}}'
  loop:
    - 'server {{SERVERIP}}'
    - 'driftfile /var/lib/ntp/ntp.drift'
    - 'statistics loopstats peerstats clockstats'
    - 'filegen loopstats file loopstats type day enable'
    - 'filegen peerstats file peerstats type day enable'
    - 'filegen clockstats file clockstats type day enable'
    - 'restrict -4 default kod notrap nomodify nopeer noquery'
    - 'restrict -6 default kod notrap nomodify nopeer noquery'
    - 'restrict 127.0.0.1'
    - 'restrict ::1'
    - 'restrict 192.168.10.0 mask 255.255.255.0 nomodify notrap'
    - 'disable auth'
    - 'broadcastclient'
    - '# this is the pid file that monit will check'
    - 'pidfile /var/run/ntpd.pid'
  register: config

- name: Starting service if permissions changed
  shell:
    cmd: /etc/rc.d/rc.ntpd restart
  when:
    ntpd.changed or config.changed
    