- name: Copy config files
  tags: monit
  template:
    src: "{{item}}.j2"
    dest: "/{{item}}"
    backup: yes
  loop:
    - etc/monit.d/CLIENT-monitrc
  notify:
    - Restart monit

- name: Activate monit service
  tags: monit
  file:
    path: /etc/rc.d/rc.monit
    mode: +x
  notify:
    - Restart monit
