- name: Copy config files
  tags: client,monit
  template:
    src: "{{item}}.j2"
    dest: "/{{item}}"
    backup: yes
  loop:
    - etc/monit.d/CLIENT-monitrc
  notify:
    - Restart monit

- name: Activate monit service
  tags: client,monit
  file:
    path: /etc/rc.d/rc.monit
    mode: +x
  notify:
    - Restart monit

- name: Copying auxiliary scripts
  tags: client,monit
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
    mode: 0755
  loop:
    - usr/local/bin/check_dns.sh
