---
- name: Verify gmond is installed
  stat:
    path: /usr/sbin/gmond
  register: gmond

- name: Copying config files
  copy:
    src: '{{item}}'
    dest: '/{{item}}'
    backup: yes
  loop:
    - etc/ganglia/gmond.conf
    - etc/ganglia/gmetad.conf
  register: config
  when:
    gmond.stat.exists

- name: Adding ganglia config to httpd server
  lineinfile:
    path: /etc/httpd/httpd.conf
    regexp: '^{{item}}'
    line: '{{item}}'
    backup: yes
  loop:
    - 'Include /etc/httpd/extra/ganglia.conf'
  register: httpd
  when:
    gmond.stat.exists

- name: Activate mod_conf in httpd
  replace:
    dest: /etc/httpd/httpd.conf
    regexp: '^#{{item}}'
    replace: '{{item}}'
    backup: yes 
  loop:
    - 'Include /etc/httpd/mod_php.conf'
  register: httpd2
  when:
    gmond.stat.exists

- name: Copying http ganglia config
  copy:
    src: '{{item}}'
    dest: '/{{item}}'
  loop:
    - etc/httpd/extra/ganglia.conf
  register: httpd3
  when:
    gmond.stat.exists

- name: Linking gmond conf
  shell:
    cmd: ln -s /etc/ganglia/gmond.conf /etc/

- name : Activating services
  file:
    path: '/etc/rc.d/rc.{{item}}'
    mode: +x
  loop:
    - httpd
    - gmetad
    - gmond
  register: services
  when:
    gmond.stat.exists

- name: Restarting services if needed
  shell:
    cmd: '/etc/rc.d/rc.{{item}} restart'
  loop:
    - 'httpd'
    - 'gmetad'
    - 'gmond'
  when:
    config.changed or httpd.changed or httpd2.changed or httpd3.changed  or services.changed      

