---
- hosts: "{{ variable_host | default('clients') }}"
  vars:
    network_available: true
  gather_facts: false
  vars_files:
    - vars/main.yml
    - client_secrets.yml
  roles:
    # - ../common/roles/proxy
    - ../common/roles/shutdownperms
    - ../common/roles/wakeonlan
    - network
    - ntpd
    - nfs
    - nis
    - crontab
    - rootpassword
    - ../common/roles/monit
    - monit
    - x2go
    - ../common/roles/ganglia
    - ../common/roles/netdata
    - harddisk
    - ../common/roles/motd
    - pip
