# ansible-playbook -i inventory client.yml  --tags client --connection-password-file .client_password.txt
---
- hosts: "{{ variable_host | default('clients') }}"
  vars:
    network_available: true
  gather_facts: false
  vars_files:
    - vars/main.yml
    - client_secrets.yml
  roles:
    # - ../common/roles/proxy
    - ../common/roles/shutdownperms
    - ../common/roles/wakeonlan
    - network
    - ntpd
    - nfs
    - nis
    - crontab
    - rootpassword
    - harddisk
    - ../common/roles/motd
    - ../common/roles/virtualbox
    - lilo
    - swap
    - ../common/roles/monit
    - monit
    - nhc
    - pip
    - ../common/roles/cpu_control
    - ../common/roles/mem_cpu_control
    - ../common/roles/netdata
    - x2go
    - ../common/roles/ganglia
    - ../common/roles/tailscale
