---
- hosts: all
  vars:
    network_available: true
  vars_files:
    - vars/main.yml
  roles:
    - ../common/roles/proxy
    - ../common/roles/shutdownperms
    - ../common/roles/wakeonlan
    - network
    - ntpd
    - nfs
    - nis
    - crontab
    - ../common/roles/monit
    - monit
    - x2go
    - ../common/roles/ganglia

