---
- name: Verify gmond is installed
  tags: server, ganglia
  stat:
    path: /usr/sbin/gmond
  register: gmond
  failed_when: not gmond.stat.exists

# - name: Verify bind option is UNCOMMENTED in gmond for receiving traffice (must be commented on client)
#   lineinfile:
#     dest: /etc/ganglia/gmond.conf
#     line: '  bind = {{SERVERIP}}'
#     insertafter: '.*#bind = SERVERIP.*'
#     backup: yes
#   register: gmondconfig
# - name: Restart gmond service if config changed
#   shell:
#     cmd: /etc/rc.d/rc.gmond restart
#   when:
#     gmondconfig.changed

- name: Adding ganglia config to httpd server
  tags: server, ganglia
  lineinfile:
    path: /etc/httpd/httpd.conf
    regexp: '^{{item}}'
    line: '{{item}}'
    backup: yes
  loop:
    - 'Include /etc/httpd/extra/ganglia.conf'
  register: httpd

- name: Activate mod_conf in httpd
  tags: server, ganglia
  replace:
    dest: /etc/httpd/httpd.conf
    regexp: '^#{{item}}'
    replace: '{{item}}'
    backup: yes 
  loop:
    - 'Include /etc/httpd/mod_php.conf'
  register: httpd2

- name: Copying http ganglia config
  tags: server, ganglia
  copy:
    src: '{{item}}'
    dest: '/{{item}}'
  loop:
    - etc/httpd/extra/ganglia.conf
  register: httpd3

- name: Copying gmetad ganglia config
  tags: server, ganglia
  template:
    src: '{{item}}.j2'
    dest: '/{{item}}'
  loop:
    - etc/ganglia/gmetad.conf
  register: gmetadconf

- name : Activating services
  tags: server, ganglia
  file:
    path: '/etc/rc.d/rc.{{item}}'
    mode: +x
  loop:
    - httpd
    - gmetad
  register: services

- name: Restarting services if needed
  tags: server, ganglia
  shell:
    cmd: '/etc/rc.d/rc.{{item}} restart'
  loop:
    - 'httpd'
    - 'gmetad'
  when:
    httpd.changed or httpd2.changed or httpd3.changed  or services.changed or gmetadconf.changed
