# PUT ALL PASSWORDS in the file passwords.yml in the main playbook dir

# nis
NISDOMAIN: 'salafisnis'

# sshd
# ROOTLOGIN could be either yes or prohibit-password when the
# public key has been copied
ROOTLOGIN: 'prohibit-password'

# Local proxy
PROXY: '192.168.10.1:3128'
