# PUT ALL PASSWORDS in the file passwords.yml in the main playbook dir

# Server internal ip
BASE_SERVERIP: '192.168.10'
SERVERIP: '{{BASE_SERVERIP}}.1'
SERVERIP_EXT: '168.176.35.111'
SERVER_DOMAINNAME: 'salafis'
SERVER_NAME: 'server{{SERVER_DOMAINNAME}}'

# Local proxy
PROXY: '{{SERVERIP}}:3128'

# nis
NISDOMAIN: 'salafisnis'

# sshd
# ROOTLOGIN could be either yes or prohibit-password when the
# public key has been copied
ROOTLOGIN: 'prohibit-password'

