---
- name: Copying networkmanager hook (NEEDED??)
  tags: network
  copy:
    src: '{{item}}'
    dest: '/{{item}}'
  loop:
    - etc/NetworkManager/dispatcher.d/90networkmanagerhook.sh
  notify: Restart networkmanager

- name: Activating network manager service
  tags: network
  file:
    path: /etc/rc.d/rc.networkmanager
    mode: +x
  notify: Restart networkmanager
