---
- name: Decrypt hosts file
  shell:
    cmd: 'cd {{playbook_dir}}/files/etc; echo {{DNSMASQHOSTPASSWORD}} | openssl enc -d -aes-256-cbc -iter 10 -salt -in {{ item }}.enc -out {{ item }} -pass stdin'
    creates: "files/etc/{{ item }}"
  loop:
    - dnsmasq-hosts.conf

- name: Copy dnsmasq config files
  copy:
    src: etc/{{ item }}
    dest: /etc/{{ item }}
    owner: root
    group: root
    backup: yes 
  loop:
    - dnsmasq-hosts.conf

- name: Copy hosts file 
  template:
    src: '{{item}}.j2'
    dest: '/{{item}}'
    owner: root
    group: root
    backup: yes 
  loop:
    - etc/hosts
    - etc/dnsmasq.conf

- name: Copy dnsmasq startup rc file with exec mode
  copy:
    src: etc/{{ item }}
    dest: /etc/{{ item }}
    owner: root
    group: root
    mode: a+x
    backup: yes 
  loop:
    - rc.d/rc.dnsmasq
  register: dnsmasq

- name: Start dnsmasq if the rc file has been copied
  command:
    /etc/rc.d/rc.dnsmasq restart
  when:
    dnsmasq.changed == True
