---
#- name: Decrypt hosts file (NOT NEDEED, NOW USING ansible-vault)
#  tags: dnsmasq,server
#  shell:
#    cmd: 'cd {{playbook_dir}}/files/etc; echo {{DNSMASQHOSTPASSWORD}} | openssl enc -d -aes-256-cbc -iter 10 -salt -in {{ item }}.enc -out {#{ item }} -pass stdin'
#    creates: "files/etc/{{ item }}"
#  loop:
#    - dnsmasq-hosts.conf

- name: Decrypt and copy dnsmasq-host config files
  tags: dnsmasq,server
  copy:
    src: etc/{{ item }}
    dest: /etc/{{ item }}
    owner: root
    group: root
    backup: yes 
  loop:
    - dnsmasq-hosts.conf
  notify: Restart dnsmasq

- name: Copy hosts and config file 
  tags: dnsmasq,server
  template:
    src: '{{item}}.j2'
    dest: '/{{item}}'
    owner: root
    group: root
    backup: yes 
  loop:
    - etc/hosts
    - etc/dnsmasq.conf
  notify: Restart dnsmasq

- name: Copy dnsmasq startup rc file with exec mode
  tags: dnsmasq,server
  copy:
    src: etc/{{ item }}
    dest: /etc/{{ item }}
    owner: root
    group: root
    mode: a+x
    backup: yes 
  loop:
    - rc.d/rc.dnsmasq
  notify: Restart dnsmasq

