---
- name: Copy resolv conf files
  tags: server,network
  copy:
    src: '{{item}}'
    dest: '/{{item}}'
    owner: root
    group: root
    mode: '0644'
    backup: yes 
  loop:
    - etc/resolv.conf.head

- name: Copy network interfaces config files
  tags: server,network
  template:
    src: '{{item}}.j2'
    dest: '/{{item}}'
    owner: root
    group: root
    mode: '0644'
    backup: yes 
  loop:
    - etc/rc.d/rc.inet1.conf

- name: Copy hostname template
  tags: server,network
  template:
    src: '{{item}}.j2'
    dest: '/{{item}}'
    backup: yes 
  loop:
    - etc/HOSTNAME

#- name: Adding executable status for network manager (TODO-> Is this really needed?)
#  tags: server,network
#  file:
#    dest: /etc/rc.d/rc.networkmanager
#    mode: a+x
#  register: netmanager

#- name: Start network manager if it has been just made executable
#  tags: server,network
#  command:
#    /etc/rc.d/rc.networkmanager restart
#  when:
#    netmanager.changed == True
