---
- name: Copying minute maintenance script
  template:
    src: "{{item}}.j2"
    dest: "/{{item}}"
    mode: 0755
  loop:
    - usr/local/bin/minute_maintenance.sh
  register: minutescript

- name: Adding minute_maintenance job
  cron:
    name: "Run useful script every minute"
    minute: "*/1"
    job: "/bin/bash /usr/local/bin/minute_maintenance.sh &>/var/log/minute_maintenance.log"
  register: minutejob

- name: Copying script to check client_status
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
    mode: 0755
  loop:
    - usr/local/bin/clients_status.sh
  register: clientstatusscript

- name: Update client status every 5 minutes
  cron:
    name: "Update clients status"
    minute: "*/5"
    job: "/bin/bash /usr/local/bin/clients_status.sh &>/var/log/clients_status.log"
  register: clientstatusjob

- name: Copying daily maintenance script
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
  loop:
    - etc/cron.daily/daily_maintenance.sh
  register: daily

- name: Restart service in config changed
  command:
    cmd: /etc/rc.d/rc.crond restart
  when:
    minutescript.changed or minutejob.changed or clientstatusscript.changed or clientstatusjob.changed or daily.changed
