---
- name: Adding minute_maintenance job
  cron:
    name: "Run useful script every minute"
    minute: "*/1"
    job: "/bin/bash /root/repos/computer-labs/computer-room/files/SERVER-cron/minute_maintenance.sh &>/var/log/minute_maintenance.log"
  register: minute

- name: Update motd every 10 minutes
  cron:
    name: "Update motd"
    minute: "*/10"
    job: "/bin/bash /root/repos/computer-labs/computer-room/files/SERVER-cron/update_motd.sh &>/var/log/update_motd.log"
  register: motd

- name: Copying daily maintenance script
  copy:
    src: "{{item}}"
    dest: "/{{item}}"
  loop:
    - etc/cron.daily/daily_maintenance.sh
  register: daily

- name: Restart service in config changed
  command:
    cmd: /etc/rc.d/rc.crond restart
  when:
    minute.changed or motd.changed or daily.changed
 