# # ansible-playbook -f 30 -i inventory hpc_salafis.yml  --tags hpc_server --connection-password-file .client_password.txt --check
# ansible-playbook -e 'all=localhost' ansible/slackware/extra_packages.yml 
---
- hosts: "{{ variable_host | default('hpc_all') }}"
  vars:
    network_available: true
  gather_facts: false
  # vars_files:
  #   - vars/main.yml
  #   - client_secrets.yml
  roles:
    - pkgs
    - munge
    - slurm
    - openmpi


# TODO:
# - Fix ganglia not being installed but being confused with ganglia-web